# Generated by Django 2.2.1 on 2019-05-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='released',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
