# Generated by Django 2.2.1 on 2019-05-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
